---
title: "R Notebook"
output: html_notebook
---

# R Project

## Introduction

## Questions

## Retrieve dataset and define necessary functions

```{r}

library(readr)
library(dplyr)
library(ggplot2)

us_births_2016_2021 <- read_csv("data/us_births_2016_2021.csv")
View(us_births_2016_2021)
```

## Q1: How does the number of births change from 2016 to 2021? 

```{r}
#Group the years and number of births 
year_Numberofbirths <- us_births_2016_2021[c('Year','Number of Births')]

#Create new data frame for births and years 
yearbirthDF <- year_Numberofbirths %>% 
  group_by(Year) %>% 
  summarize(Births = sum(`Number of Births`))

#plot 
xYears <- c(yearbirthDF$Year)
yBirths <- c(yearbirthDF$Births)

ggplot(yearbirthDF, aes(x=xYears, y=yBirths)) +
   geom_line()+
   ggtitle("Total number of Births in the US from 2016 to 2021")+
   xlab("Year")+
   ylab("Total Number of Births")
   
```

## Q2: What is the correlation between Mother's Education Level and Baby Weight? 

```{r}
#Group the education level, code and age 
ageEduWeight <- us_births_2016_2021[c(5,8,9)]


```
